### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by influxweb** [mdmoreau/minimodal#1]
Thank you for writing a lightweight and function script; I love the way it works. I was wondering if you would consider adding "inline" content as an option so a hidden element could be called in to populate the content of the modal?

Thank you,
Matt

**Comment by influxweb** [comment]
I actually was able to hack something together. I added the following and it seemed to do the trick when you pass `data-minimodal-type="image"` on the item.

```javascript
_.inline = function () {
	var url = _.url;

	if (url === _.url) {
		var inlineContent = document.querySelector(url);

		if (inlineContent.nodeName.toLowerCase() === 'img') {
			var img = document.createElement('img');
			var imgSrc = inlineContent.getAttribute('src');

			img.onload = function () {
				if (url === _.url) {
					_.content = _.node('<div class="minimodal__content"><img class="minimodal__element" src="' + imgSrc + '">');
					_.loaded();
				}
			};
			img.onerror = function () {
				if (url === _.url) {
					_.error();
				}
			};
			img.src = imgSrc;
		}
		else {
			_.content = _.node('<div class="minimodal__content"><div class="minimodal__element">' + inlineContent.innerHTML);
			_.loaded();
		}
	}
};
```

**Comment by mdmoreau** [comment]
@influxweb I know this is really, really late, but you might check out the `selector` content type that was added a while back.
