### ISSUE TITLE
Feature Request - Add title attribute to iframes

### ISSUE THREAD

**Issue by gijimmyj** [mdmoreau/minimodal#2]
To improve accessibility it would be great if we could add a title attribute to iframes

**Comment by mdmoreau** [comment]
@gijimmyj I think that makes sense, and it should be easy enough to add. Right now the title attributes on the trigger elements are being used for captions. It seems like it might be better to rework that to use data-caption instead, and then add support for data-alt for images and data-title for iframes. Then the trigger element can use the title attribute without any conflicts. Any other ideas on how to go about handling that?

**Comment by mdmoreau** [comment]
@gijimmyj Support for this has been added in 1.0.0 (https://github.com/mdmoreau/minimodal#attribute-passthrough).
