### ISSUE TITLE
onUnLoaded callback

### ISSUE THREAD

**Issue by wdmartin** [mdmoreau/minimodal#5]
It would be handy to have a callback that fires when the modal is closed.

Use case: in the course of developing a modal which contains scrolling content, we discovered that when the modal is open it is still possible to scroll the page underneath it.  On desktop this occurs with the mouse wheel; on mobile, it's possible to inadvertently drag the main viewport scrollbar while attempting to use the scrollbar on the modal content.

To fix that, we added `overflow: hidden` to the body of the document when the modal opens, using the onLoaded callback.  That needs to be removed when the modal closes so that the page will scroll normally again. We've been able to make that work by binding an extra onClick function to the `.minimodal__close` button, but we also had to set up an onKeyPress handler to listen for the Escape key while the modal is open.

That works, but it would be much cleaner if there was a native onUnLoaded callback that gets executed whenever the modal is closed, regardless of how the close was triggered.

**Comment by mdmoreau** [comment]
@wdmartin Thanks for the feedback! Got two new options added (onOpen, onClose) which are documented in the readme. They should be available in the latest version on npm - 0.8.0. Let me know if that works.

**Comment by wdmartin** [comment]
Wonderful! I've snagged the new version and updated our code to make use of onOpen and onClose. 

I believe that resolves this issue. Thanks!
