### ISSUE TITLE
Feature Request - Body Class

### ISSUE THREAD

**Issue by jared-thompson** [mdmoreau/minimodal#7]
Add a body class when the modal is opened and removed when closed.

While this can be done with `onOpen` and `onClose`, we use minimodal with a few different configurations on our site. Adding a body class as a default feature helps prevent us from having to define the same code in multiple instances to do the same thing.

Depending on one's needs, this creates a nice little hook for when you need to make modifications like `body { overflow: hidden; }`.

**Example**

```js
_.build = function() {
  // ...
  document.body.classList.add( 'minimodal-open' );
  // ...
}

_.close= function() {
  // ...
  document.body.classList.remove( 'minimodal-open' );
  // ...
}
```

Thanks!

**Comment by jared-thompson** [comment]
Also, would it be possible to make the video query parameters configurable? While many browsers are restricting autoplay for videos, especially on mobile, it would be nice to set the value `autoplay`, along with `ref`, to what would work best for the end-user.

**Comment by mdmoreau** [comment]
@jared-thompson version 1.1.0 toggles a data-minimodal-active attribute on the document root, which should handle the first request.

Do you have an example of video query params that aren't working? They should be implemented for YouTube (just tested autoplay), but I haven't had a need for those on other services yet.

**Comment by jared-thompson** [comment]
Thanks @mdmoreau for adding that `data-` attribute!

Sorry, about the confusion with video player parameters. You can ignore that.

We had a third-party implement a bunch of our front-end code when our site first released. Since then, we have taken over all site development and I assumed, incorrectly, that the `autoplay=1` I was seeing in the source for video types was from minimodal and not the third-party. The third-party had made a lot of custom, and quite conditional, modifications that could have been implemented outside of the code (especially since there are `onOpen` and `onClose` methods) and it looks like the `autoplay` query param was another one their modifications.

**Comment by mdmoreau** [comment]
@jared-thompson Happy to help! Going to close this out, but feel free to open another issue if you see other potential improvements.
